services:
  - type: web
    name: saudi-stock-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DISCORD_WEBHOOK_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
